import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";

import ToggleThemeButton from "@/components/miela/toggleTheme";
import SideBar from "@/components/miela/sidebar";
import { Providers } from "./providers";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Change Electronics Asset Management",
  description: "Generated by create next app",
  // icons: /"/change_logo.png" ,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="flex">
            <div
              id="left-sidebar"
              className="flex p-4 flex-col justify-center items-start pt-8 fixed h-screen xl:w-1/5 lg:1/4 bg-gray-900 dark:bg-black"
            >
              <Link href="/">
                <div className="mb-8 text-white flex  justify-center items-center font-mono font-bolder">
                  <Image
                    src="/change logo.png"
                    alt="logo image"
                    width="72"
                    height="72"
                  />
                  <h3>Change Electronics</h3>
                </div>
              </Link>
              <SideBar />
              {/* <div><Link href="/dashboard">Dashboard</Link> <Separator /></div> */}
              <div className="flex-1"></div>
              <ToggleThemeButton className="ml-auto"></ToggleThemeButton>
            </div>
            <div id="right-sidebar" className="ml-[20%] w-full">
              <div className="p-4">{children}</div>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
